<?php
/**
 * EstimationRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Parenthesis\DingConnect
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ding API
 *
 * Important note: If you are within DingConnect, your API key is displayed above and can be used to access and send top-up from your system via the Ding API.    The Ding API is a Level 0 REST web service.  We have used the <a href=\"http://swagger.io\">swagger</a> standard to describe this service. As a result, we are able to provide this interactive documentation page. For further information, you may view the <a href=\"/api/description\">additional documentation</a>; read our <a href=\"/api/faq\">FAQ</a> or contact partnersupport@ding.com
 *
 * OpenAPI spec version: V1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Parenthesis\DingConnect\Model;

use \ArrayAccess;
use \Parenthesis\DingConnect\ObjectSerializer;

/**
 * EstimationRequest Class Doc Comment
 *
 * @category Class
 * @package  Parenthesis\DingConnect
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EstimationRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'EstimationRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'send_value' => 'float',
        'send_currency_iso' => 'string',
        'receive_value' => 'float',
        'sku_code' => 'string',
        'batch_item_ref' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'send_value' => 'decimal',
        'send_currency_iso' => null,
        'receive_value' => 'decimal',
        'sku_code' => null,
        'batch_item_ref' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'send_value' => 'SendValue',
        'send_currency_iso' => 'SendCurrencyIso',
        'receive_value' => 'ReceiveValue',
        'sku_code' => 'SkuCode',
        'batch_item_ref' => 'BatchItemRef'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'send_value' => 'setSendValue',
        'send_currency_iso' => 'setSendCurrencyIso',
        'receive_value' => 'setReceiveValue',
        'sku_code' => 'setSkuCode',
        'batch_item_ref' => 'setBatchItemRef'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'send_value' => 'getSendValue',
        'send_currency_iso' => 'getSendCurrencyIso',
        'receive_value' => 'getReceiveValue',
        'sku_code' => 'getSkuCode',
        'batch_item_ref' => 'getBatchItemRef'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['send_value'] = isset($data['send_value']) ? $data['send_value'] : null;
        $this->container['send_currency_iso'] = isset($data['send_currency_iso']) ? $data['send_currency_iso'] : null;
        $this->container['receive_value'] = isset($data['receive_value']) ? $data['receive_value'] : null;
        $this->container['sku_code'] = isset($data['sku_code']) ? $data['sku_code'] : null;
        $this->container['batch_item_ref'] = isset($data['batch_item_ref']) ? $data['batch_item_ref'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['sku_code'] === null) {
            $invalidProperties[] = "'sku_code' can't be null";
        }
        if ($this->container['batch_item_ref'] === null) {
            $invalidProperties[] = "'batch_item_ref' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets send_value
     *
     * @return float
     */
    public function getSendValue()
    {
        return $this->container['send_value'];
    }

    /**
     * Sets send_value
     *
     * @param float $send_value Desired send value
     *
     * @return $this
     */
    public function setSendValue($send_value)
    {
        $this->container['send_value'] = $send_value;

        return $this;
    }

    /**
     * Gets send_currency_iso
     *
     * @return string
     */
    public function getSendCurrencyIso()
    {
        return $this->container['send_currency_iso'];
    }

    /**
     * Sets send_currency_iso
     *
     * @param string $send_currency_iso The currency of `SendValue`
     *
     * @return $this
     */
    public function setSendCurrencyIso($send_currency_iso)
    {
        $this->container['send_currency_iso'] = $send_currency_iso;

        return $this;
    }

    /**
     * Gets receive_value
     *
     * @return float
     */
    public function getReceiveValue()
    {
        return $this->container['receive_value'];
    }

    /**
     * Sets receive_value
     *
     * @param float $receive_value Desired receive value
     *
     * @return $this
     */
    public function setReceiveValue($receive_value)
    {
        $this->container['receive_value'] = $receive_value;

        return $this;
    }

    /**
     * Gets sku_code
     *
     * @return string
     */
    public function getSkuCode()
    {
        return $this->container['sku_code'];
    }

    /**
     * Sets sku_code
     *
     * @param string $sku_code Product to estimate a price for
     *
     * @return $this
     */
    public function setSkuCode($sku_code)
    {
        $this->container['sku_code'] = $sku_code;

        return $this;
    }

    /**
     * Gets batch_item_ref
     *
     * @return string
     */
    public function getBatchItemRef()
    {
        return $this->container['batch_item_ref'];
    }

    /**
     * Sets batch_item_ref
     *
     * @param string $batch_item_ref A unique reference for an item in a batched request.
     *
     * @return $this
     */
    public function setBatchItemRef($batch_item_ref)
    {
        $this->container['batch_item_ref'] = $batch_item_ref;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


