<?php
/**
 * PriceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Parenthesis\DingConnect
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ding API
 *
 * Important note: If you are within DingConnect, your API key is displayed above and can be used to access and send top-up from your system via the Ding API.    The Ding API is a Level 0 REST web service.  We have used the <a href=\"http://swagger.io\">swagger</a> standard to describe this service. As a result, we are able to provide this interactive documentation page. For further information, you may view the <a href=\"/api/description\">additional documentation</a>; read our <a href=\"/api/faq\">FAQ</a> or contact partnersupport@ding.com
 *
 * OpenAPI spec version: V1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Parenthesis\DingConnect;

/**
 * PriceTest Class Doc Comment
 *
 * @category    Class
 * @description Price
 * @package     Parenthesis\DingConnect
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PriceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Price"
     */
    public function testPrice()
    {
    }

    /**
     * Test attribute "customer_fee"
     */
    public function testPropertyCustomerFee()
    {
    }

    /**
     * Test attribute "distributor_fee"
     */
    public function testPropertyDistributorFee()
    {
    }

    /**
     * Test attribute "receive_value"
     */
    public function testPropertyReceiveValue()
    {
    }

    /**
     * Test attribute "receive_currency_iso"
     */
    public function testPropertyReceiveCurrencyIso()
    {
    }

    /**
     * Test attribute "receive_value_excluding_tax"
     */
    public function testPropertyReceiveValueExcludingTax()
    {
    }

    /**
     * Test attribute "tax_rate"
     */
    public function testPropertyTaxRate()
    {
    }

    /**
     * Test attribute "tax_name"
     */
    public function testPropertyTaxName()
    {
    }

    /**
     * Test attribute "tax_calculation"
     */
    public function testPropertyTaxCalculation()
    {
    }

    /**
     * Test attribute "send_value"
     */
    public function testPropertySendValue()
    {
    }

    /**
     * Test attribute "send_currency_iso"
     */
    public function testPropertySendCurrencyIso()
    {
    }
}
