<?php
/**
 * PromotionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Parenthesis\DingConnect
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ding API
 *
 * Important note: If you are within DingConnect, your API key is displayed above and can be used to access and send top-up from your system via the Ding API.    The Ding API is a Level 0 REST web service.  We have used the <a href=\"http://swagger.io\">swagger</a> standard to describe this service. As a result, we are able to provide this interactive documentation page. For further information, you may view the <a href=\"/api/description\">additional documentation</a>; read our <a href=\"/api/faq\">FAQ</a> or contact partnersupport@ding.com
 *
 * OpenAPI spec version: V1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Parenthesis\DingConnect;

/**
 * PromotionTest Class Doc Comment
 *
 * @category    Class
 * @description Promotion
 * @package     Parenthesis\DingConnect
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PromotionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Promotion"
     */
    public function testPromotion()
    {
    }

    /**
     * Test attribute "provider_code"
     */
    public function testPropertyProviderCode()
    {
    }

    /**
     * Test attribute "start_utc"
     */
    public function testPropertyStartUtc()
    {
    }

    /**
     * Test attribute "end_utc"
     */
    public function testPropertyEndUtc()
    {
    }

    /**
     * Test attribute "currency_iso"
     */
    public function testPropertyCurrencyIso()
    {
    }

    /**
     * Test attribute "validity_period_iso"
     */
    public function testPropertyValidityPeriodIso()
    {
    }

    /**
     * Test attribute "minimum_send_amount"
     */
    public function testPropertyMinimumSendAmount()
    {
    }

    /**
     * Test attribute "localization_key"
     */
    public function testPropertyLocalizationKey()
    {
    }
}
