<?php
/**
 * V1ApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Parenthesis\DingConnect
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ding API
 *
 * Important note: If you are within DingConnect, your API key is displayed above and can be used to access and send top-up from your system via the Ding API.    The Ding API is a Level 0 REST web service.  We have used the <a href=\"http://swagger.io\">swagger</a> standard to describe this service. As a result, we are able to provide this interactive documentation page. For further information, you may view the <a href=\"/api/description\">additional documentation</a>; read our <a href=\"/api/faq\">FAQ</a> or contact partnersupport@ding.com
 *
 * OpenAPI spec version: V1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Parenthesis\DingConnect;

use \Parenthesis\DingConnect\Configuration;
use \Parenthesis\DingConnect\ApiException;
use \Parenthesis\DingConnect\ObjectSerializer;

/**
 * V1ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Parenthesis\DingConnect
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class V1ApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cancelTransfers
     *
     * Attempt to cancel transfers with the submitted TransferIds.
     *
     */
    public function testCancelTransfers()
    {
    }

    /**
     * Test case for estimatePrices
     *
     * Estimate prices for send or receive values.
     *
     */
    public function testEstimatePrices()
    {
    }

    /**
     * Test case for getAccountLookup
     *
     * Get providers and product information for a specific account number.
     *
     */
    public function testGetAccountLookup()
    {
    }

    /**
     * Test case for getBalance
     *
     * Get the current agent balance.
     *
     */
    public function testGetBalance()
    {
    }

    /**
     * Test case for getCountries
     *
     * Get a list of supported countries.
     *
     */
    public function testGetCountries()
    {
    }

    /**
     * Test case for getCurrencies
     *
     * Get a list of supported currencies.
     *
     */
    public function testGetCurrencies()
    {
    }

    /**
     * Test case for getErrorCodeDescriptions
     *
     * Get a list of error code descriptions.
     *
     */
    public function testGetErrorCodeDescriptions()
    {
    }

    /**
     * Test case for getProductDescriptions
     *
     * Get localized strings for products.
     *
     */
    public function testGetProductDescriptions()
    {
    }

    /**
     * Test case for getProducts
     *
     * Get a list of products that can be used in SendTransfer.
     *
     */
    public function testGetProducts()
    {
    }

    /**
     * Test case for getPromotionDescriptions
     *
     * Get localized strings for promotions.
     *
     */
    public function testGetPromotionDescriptions()
    {
    }

    /**
     * Test case for getPromotions
     *
     * Get a list of promotions.
     *
     */
    public function testGetPromotions()
    {
    }

    /**
     * Test case for getProviderStatus
     *
     * Get the current status of product providers.
     *
     */
    public function testGetProviderStatus()
    {
    }

    /**
     * Test case for getProviders
     *
     * Get a list of product providers available to the agent.
     *
     */
    public function testGetProviders()
    {
    }

    /**
     * Test case for getRegions
     *
     * Get a list of regions on the system.
     *
     */
    public function testGetRegions()
    {
    }

    /**
     * Test case for listTransferRecords
     *
     * Query transfers that were submitted to the system.
     *
     */
    public function testListTransferRecords()
    {
    }

    /**
     * Test case for sendTransfer
     *
     * Send a transfer to an account.
     *
     */
    public function testSendTransfer()
    {
    }
}
